name: "Push Export"
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - "feat/**"

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: graphic-viewer

jobs:
  export-windows:
    if: true
    name: Windows Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:mono-4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: |
          mkdir -v -p builds/windows
          godot --headless --export-release "Windows Desktop" ./builds/windows/$EXPORT_NAME.exe
          zip -r graphic-viewer_windows-x86_64.zip builds/windows/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: builds/windows
          retention-days: 1
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: graphic-viewer_windows-x86_64.zip
