name: release.yml
on:
  release: 
    types: [prereleased, released]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:mono-4.4.1
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: |
          mkdir -v -p builds/windows
          godot --headless --export-release "Windows Desktop" ./builds/windows/$EXPORT_NAME.exe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/windows/$EXPORT_NAME.exe
          asset_name: $EXPORT_NAME.exe
          tag: ${{ github.ref }}
          overwrite: true